### ISSUE TITLE
Add Named annotation to all Async methods

### ISSUE THREAD

**Issue by adriancole** [jclouds/legacy-jclouds#1184]
In order to allow stable per-operation configuration, we need to name methods that correspond to rest actions.  This directly support smarter timeouts in issue #1089.

For example, in AWS, names are already present on all async ops following IAM naming conventions like `s3:PutObject`.  Using constants names will replace the old `Class.method` syntax, which is especially brittle in openstack and ec2 clones who have vastly different timeouts, and also brittle when method names are refactored, or multiple methods execute the same command.

This issue will track addition of similar annotations for all async apis, and closes when we can remove the former property syntax.

- [x] aws: issue #1185: IAM naming conventions ex. `s3:PutObject`
- [x] rackspace: issue #1202: colon-delimited naming conventions ex. `server:create`
- [x] openstack: issue #1201: colon-delimited naming conventions ex. `server:create`, issue #1295 command name ex. `ListContainers`
- [x] hpcloud: issue #1295 command name ex. `ListContainers`
- [x] google: issue #1224:  colon-delimited naming conventions ex. `Disk:insert`
- [x] oauth: issue #1225: ex. `authenticate`
- [x] chef: [issue: #55](https://github.com/jclouds/jclouds-chef/pull/55): colon-delimited naming conventions ex. `cookbook:delete`
- [x] azure: issue #1293: command name ex. `ListContainers`
- [x] abiquo: issue #1197: colon-delimited naming conventions ex. `server:create`
- [ ] joyent
- [ ] opsource
- [ ] savvis
- [x] glesys: issue #1188: colon-delimited naming conventions ex. `server:create`
- [ ] cdmi
- [x] fgcp: Issue #1232: command name ex. `GetVDiskStatus`
- [ ] jenkins
- [ ] trmk
- [ ] softlayer
- [ ] elasticstack
- [ ] cloudsigma
- [x] atmos: issue #1292: command name ex. `ListContainers`
- [ ] gogrid
- [x] cloudstack: issue #1296: command name ex. `listVirtualMachines`
- [ ] vcloud (coherent w/ vcloud-director)

**Comment by andrewgaul** [comment]
Async removed  in 1.9.0.
