### ISSUE TITLE
Transition to ASF

### ISSUE THREAD

**Issue by codefromthecrypt** [jclouds/legacy-jclouds#1576]
This meta-issue will help organize folks as we transition into apache incubation.  With shared understanding, we can work together to get tasks done and hack in the ASF as soon as possible.   Feel free to add or revise tasks, and update this as we progress.  

cc apache mentors: @brianm @tomwhite @hgschmie @ke4qqq @jbonofre @mnour @olamy @kami @smarru @carlossg
### Tasks
- [x] Monday morning, April 29th, we can close the vote for jclouds to enter [Apache Incubation](http://wiki.apache.org/incubator/jcloudsProposal)
- [x] request jclouds [podling creation](http://www.apache.org/dev/infra-contact#requesting-podling)
- [x] request ml jclouds-dev: for development discussions
- [x] request ml jclouds-user: for community discussions
- [x] request ml jclouds-private: for PPMC discussions
- [x] request ml jclouds-commits: for code changes
- [x] request git repo `incubator-jclouds` from `jclouds/jclouds`, following [this example](https://issues.apache.org/jira/browse/INFRA-5961)
- [x] send notication to jclouds and jclouds-dev google groups noting our new locations
- [x] ensure all initial committers have an ICLA on file with the ASF
